require 'rubygems'
require 'rake/dsl_definition'
require 'rubygems/package_task'
require 'rake/testtask'

spec = Gem::Specification.new do |s|
  s.name = "eideticpdf"
  s.version = "1.0.1"
  s.date = "2013-12-03"
  s.summary = "PDF Library"
  s.requirements = "Ruby 1.8.7 or 1.9.3"
  s.author = "Brent Rowland"
  s.email = "rowland@rowlandresearch.com"
  s.homepage = "https://github.com/rowland/eideticpdf"
  s.rubyforge_project = "eideticpdf"
  s.test_file = "test/pdf_tests.rb"
  s.has_rdoc = true
  s.rdoc_options << '--title' << 'Eidetic PDF' << '--main' << 'lib/epdfdw.rb' << '-x' << 'test'
  s.files = FileList["lib/*.rb"] + FileList["test/test*.rb"] + ['test/testimg.jpg'] + FileList["fonts/*.afm"] + FileList["fonts/*.inf"]
  s.platform = Gem::Platform::RUBY
end

Gem::PackageTask.new(spec) do |pkg|
  pkg.need_tar = false
  pkg.need_zip = false
end

Rake::TestTask.new do |t|
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end

desc "Clean up files generated by tests."
task :clean do
  rm_f "test.pdf"
  rm_f "encoding_test.pdf"
  rm_f "test/test.pdf"
  rm_f "test/encoding_test.pdf"
end

desc "Build documentation."
task :doc do
  `ruby doc/build_documentation.rb`
end
